version: '3.8'

services:
  api-gateway:
    container_name: gateway
    build: ./api-gateway/
    ports:
      - "5000:5000"
    volumes:
      - ./api-gateway:/app
    environment:
      - SERVICE_NAME_CA=http://codebase-analyzer:3001
  Code-Optimizer:
    container_name: code-optimizer
    build: ./services/Code-Optimizer
    volumes:
      - ./services/Code-Optimizer:/app
  codebase-analyzer:
    container_name: codebase-analyzer
    build: ./services/Codebase-Analyzer
    volumes:
      - ./services/Codebase-Analyzer:/app
  

